nuxeo/nuxeo-ai

- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DataSetBulkAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/RecordWriterBatchComputation.java
- nuxeo-ai-model/src/main/resources/OSGI-INF/ai-bulk.xml
The policy defines retries, fallback and batching properties for computation
that extends AbstractBatchComputation.
> NXP-26145: Policy is now part of the settings

- nuxeo-ai-core/src/main/java/org/nuxeo/ai/bulk/RecordWriter.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/tensorflow/TFRecordWriter.java
- nuxeo-ai-core/src/test/java/org/nuxeo/ai/bulk/BadRecordWriter.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DataSetBulkAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DataSetExportStatusComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportBulkProcessed.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/RecordWriterBatchComputation.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/DatasetExportTest.java
This can't be merged until NXP-27566 is fixed and backported.
> NXP-27565: Report dataset export start/stop/errors

- nuxeo-ai-core/src/main/java/org/nuxeo/ai/bulk/RecordWriter.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/tensorflow/TFRecordWriter.java
- nuxeo-ai-core/src/test/java/org/nuxeo/ai/bulk/BadRecordWriter.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DataSetBulkAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DataSetExportStatusComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportBulkProcessed.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/RecordWriterBatchComputation.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/DatasetExportTest.java
This pull request needs to wait for the fix for NXP-27566 in 10.10-HF09 before merging, otherwise the tests will fail.
> NXP-27565: Report dataset export start/stop/errors 10.10

- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/formatters/nuxeo-default-ai-suggestion-formatter.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/formatters/nuxeo-directory-ai-suggestion-formatter.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/formatters/nuxeo-document-ai-suggestion-formatter.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/formatters/nuxeo-user-group-ai-suggestion-formatter.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-suggestion-formatter-styles.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-suggestion-formatters.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-suggestion-mixin.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-suggestion.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-suggestions.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai.html
Backport of nuxeo/nuxeo-web-ui#648 to 10.10.
> NXP-27119: make AI suggestions customizable (10.10)

- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/formatters/nuxeo-default-ai-suggestion-formatter.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-suggestions.html
Backport of nuxeo/nuxeo-web-ui#669.
> NXP-27785: update AI suggestion value property name

- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/admin/admin-ai-advanced-export.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/admin/admin-ai-export.html
following a suggestion from webui team
> Improvement nxp 27115 removing poll method

- Jenkinsfile
- addons/nuxeo-ai-aws-package/src/main/assemble/assembly.xml
- addons/nuxeo-ai-aws-package/src/main/resources/package.xml
- addons/nuxeo-ai-image-quality-package/src/main/assemble/assembly.xml
- addons/nuxeo-ai-image-quality-package/src/main/resources/package.xml
- nuxeo-ai-core-package/src/main/assemble/assembly.xml
- nuxeo-ai-core-package/src/main/resources/package.xml
- pom.xml
https://jira.nuxeo.com/browse/AICORE-320
Use `org.nuxeo:nuxeo-parent:11.1-SNAPSHOT` instead of `org.nuxeo:nuxeo-ecm` 
Set `nuxeo.platform.version` and `nuxeo.target.version=11.*` target platforms.
> AICORE-320: use org.nuxeo:nuxeo-parent

- release.groovy
- tools/release.sh
https://jira.nuxeo.com/browse/AICORE-328
https://jenkins.ai.dev.nuxeo.com/blue/organizations/jenkins/nuxeo%2Frelease-nuxeo-ai/activity
> AICORE-328: release pipeline

- Jenkinsfile
- pom.xml
Fix package upload (+NOS-1265)
Fix packages archiving (`archiveArtifacts`)
Set `AWS_REGION` to avoid a warning in the logs.
Set Maven `distributionManagement`
> AICORE-320: fix upload + improvements

- Jenkinsfile
- pom.xml
- release.groovy
- tools/release.sh
Backport:
- AICORE-320: add maven-internal
- AICORE-325: Jenkinsfile
- AICORE-328: release pipeline
> AICORE-320, AICORE-325, AICORE-328 backport JX pipeline

- Jenkinsfile
- charts/preview/Chart.yaml
- charts/preview/Makefile
- charts/preview/requirements.yaml
- charts/preview/templates/nuxeo-url-configmap.yaml
- charts/preview/templates/secret-placeholder-insight-token.yaml
- charts/preview/templates/secret-placeholder-instance-clid.yaml
- charts/preview/templates/secret-placeholder-tls.yaml
- charts/preview/values.tmpl.yaml
- charts/preview/values.yaml
- docker/Dockerfile
- docker/skaffold.yaml
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-cloud-client-config.xml.nxftl
- pom.xml
- skaffold.yaml
> Feature aicore 329 preview

- Jenkinsfile
- charts/preview/Chart.yaml
- charts/preview/Makefile
- charts/preview/requirements.yaml
- charts/preview/templates/nuxeo-url-configmap.yaml
- charts/preview/templates/secret-placeholder-insight-token.yaml
- charts/preview/templates/secret-placeholder-instance-clid.yaml
- charts/preview/templates/secret-placeholder-tls.yaml
- charts/preview/values.tmpl.yaml
- charts/preview/values.yaml
- docker/Dockerfile
- docker/skaffold.yaml
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-cloud-client-config.xml.nxftl
- pom.xml
- skaffold.yaml
https://jira.nuxeo.com/browse/AICORE-329
Backport #234
> 10.10/feature aicore 329 preview

- Jenkinsfile
- charts/preview/values.tmpl.yaml
https://jira.nuxeo.com/browse/AICORE-329
Normalize namespace name. Required for branches named like `master-10.10`. 
The allowed pattern is `[a-z0-9]([-a-z0-9]*[a-z0-9])?`. All non-matching characters (like dots) are removed.
> Fix aicore 329 branch.with.dot

- Jenkinsfile
- charts/preview/values.tmpl.yaml
- docker/Dockerfile
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-cloud-client-config.xml.nxftl
Try to download packages from Connect PREPROD to get updates on Web UI from nuxeo/nuxeo-web-ui#903)
> NXP-29040: download package from PREPROD

- addons/nuxeo-ai-aws-package/src/main/resources/package.xml
- addons/nuxeo-ai-image-quality-package/src/main/resources/package.xml
Enforce fixed downstream package version to help circumvent NXP-29794
> fix AICORE-376 pkgVersion

- README.md
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/insight-enrichment-config.xml.nxftl
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/nuxeo.defaults
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/functions/SaveEnrichmentFunction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/BulkEnrichmentAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/InsightProvider.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/ModelServingService.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/TFRuntimeModel.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/BulkEnrichmentTest.java
- nuxeo-ai-model/src/test/resources/OSGI-INF/bulk-test.xml
Still need to go through the code and scrap the old behaviour + update README
> AICORE-370: insigh model serving as part of default enrih pipe

- Jenkinsfile
- charts/preview/values.tmpl.yaml
- docker/Dockerfile
- docker/skaffold.yaml
Fix too long startup by downloading the packages during build time
Continue #245, backport of #244, completes #276
> feat: INSIGHT-726 pre-download HF packages

- addons/nuxeo-ai-aws-package/src/main/resources/package.xml
- addons/nuxeo-ai-image-quality-package/src/main/resources/package.xml
Enforce packages dependency max version to avoid NXP-29794
> Fix AICORE-376 pkg deps

- Jenkinsfile
- addons/nuxeo-ai-gcp-core/src/main/java/org/nuxeo/ai/gcp/provider/ImagePropertiesEnrichmentProvider.java
- addons/nuxeo-ai-gcp-core/src/main/resources/OSGI-INF/ai-gcp-service-contrib.xml
- addons/nuxeo-ai-gcp-core/src/test/java/org/nuxeo/ai/gcp/TestService.java
- charts/preview/values.tmpl.yaml
- docker/Dockerfile
- docker/skaffold.yaml
- nuxeo-ai-core/src/main/resources/directories/ai_kinds.csv
(cherry picked from commit 498e1765a866b289cd3b5590d2f3ca2694ac4798)
> 10.10 Backport AICORE-391 gcp image properties

- addons/nuxeo-ai-gcp-core/src/main/java/org/nuxeo/ai/gcp/provider/AbstractTagProvider.java
- addons/nuxeo-ai-gcp-core/src/main/java/org/nuxeo/ai/gcp/provider/CropHintsEnrichmentProvider.java
- addons/nuxeo-ai-gcp-core/src/main/resources/OSGI-INF/ai-gcp-service-contrib.xml
- addons/nuxeo-ai-gcp-core/src/test/java/org/nuxeo/ai/gcp/TestService.java
- nuxeo-ai-core/src/main/resources/directories/ai_kinds.csv
(cherry picked from commit 7be3a36459145ef01e06f2b14566fb889f2bcc4d)
> AICORE-32: Add GCP Image Crop Hints Feature

- Jenkinsfile
- release.groovy
- tools/updatebot.sh
Same as nuxeo/nuxeo-ai-cloud#247
> ci: AICORE-424 propagate release version

- docker/Dockerfile
As of 11.x FFmpeg is not preinstalled, we must add it.
> feat: AICORE-428 install FFmpeg

- charts/preview/values.tmpl.yaml
Fix preview: mongodb is enabled without the required template
https://jenkins.ai.dev.nuxeo.com/blue/organizations/jenkins/nuxeo%2Fnuxeo-ai/detail/master-10.10/84/pipeline/﻿
> ci(AICORE-450): add mongodb template

- Jenkinsfile
- charts/preview/patch-preview.yaml
- charts/preview/requirements.yaml
- charts/preview/values.tmpl.yaml
> AICORE-455: improve preview deployment

- Jenkinsfile
- pom.xml
Fix https://jenkins.ai.dev.nuxeo.com/blue/organizations/jenkins/nuxeo%2Fnuxeo-ai/detail/master-2021/15/pipeline/
Need nuxeo-web-ui 3.0.3+
> ci(AICORE-451): nuxeo-web-ui 3.0.3

- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-webui-config.xml.nxftl
- nuxeo-ai-core/src/main/resources/OSGI-INF/ai-web-ui-properties.xml
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-bulk-add-button.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-bulk-remove-button.html
backport of https://github.com/nuxeo/nuxeo-ai/pull/364
> AICORE-457: expose nuxeo.ai.insight.client.enable property and use it… (backport 2021)

- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-webui-config.xml.nxftl
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-bulk-add-button.html
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai-bulk-remove-button.html
backport of https://github.com/nuxeo/nuxeo-ai/pull/364
> AICORE-457: expose nuxeo.ai.insight.client.enable property and use it (backport 10.10)

- Jenkinsfile
- docker/Dockerfile
- docker/skaffold.yaml
- helm/values.yaml
- nuxeo-ai-config/src/main/java/org/nuxeo/ecm/restapi/server/jaxrs/AISearchObject.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/services/ModelUsageServiceImpl.java
- nuxeo-ai-core/src/test/java/org/nuxeo/ai/enrichment/TestAutoServicesAudit.java
- nuxeo-ai-pipes/pom.xml
- pom.xml
- tools/updatebot.sh
Miscellaneous CI/CD improvements:
- cleanup
- install FFmpeg on Nuxeo instance
- workaround NXCT-548 (nuxeo/docker-nuxeo#46)
- chore(INSIGHT-788): NXP 10.10-HF42 
- pipeline review: run Maven build and tests separately, use nuxeo1010 container...
- run tests with MongoDB, ES and Kafka external services (AICORE-433)
> INSIGHT-788 misc improvements

- nuxeo-ai-config/pom.xml
- nuxeo-ai-config/src/test/java/org/nuxeo/ai/jwt/TestPKSEndpoint.java
- nuxeo-ai-model/pom.xml
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUpdateComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUploadComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportDoneComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportInitComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/cloud/CloudClient.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/cloud/NuxeoCloudClient.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/listeners/ContinuousExportListener.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/listeners/InvalidateModelDefinitionsListener.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/export/DatasetExportServiceImpl.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/export/DatasetGetModelOperation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/export/DatasetUploadOperation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/TFRuntimeModel.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/BulkEnrichmentTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/DatasetExportTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/cloud/CloudClientTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/listeners/ContinuousExportListenerTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/listeners/InvalidateModelDefinitionsListenerTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/TestCustomDocumentsTypes.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/TestDatasetOperation.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/AnnotationConfirmTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/SuggestionOpTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/TestDocsToAnnotate.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/TestModelServing.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/TestSuggestionOp.java
- nuxeo-ai-model/src/test/resources/OSGI-INF/disable-ai-listeners.xml
- nuxeo-ai-pipes/src/main/java/org/nuxeo/ai/pipes/filters/NoVersionFilter.java
- pom.xml
* INSIGHT-650: using JWT in Cloud Client
* INSIGHT-650: set prefix to project id
* INSIGHT-650: JWK PKS endpoint within AI config
Co-authored-by: Vladimir Pasquier <vpasquier@nuxeo.com>
> INSIGHT-650: using JWT in Cloud Client (#372)

- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/listeners/DocumentTranscribed.java
- addons/nuxeo-ai-aws-core/src/test/java/org/nuxeo/ai/transcribe/TestTranscribeToCaptions.java
(cherry picked from commit e95375252892d42de2ff3fb63f728858ec18875f)
> AICORE-470: Fix duplicate captions - 10.10

- addons/nuxeo-ai-aws-core/pom.xml
- addons/nuxeo-ai-aws-package/pom.xml
- addons/nuxeo-ai-aws-package/src/main/assemble/assembly.xml
- addons/nuxeo-ai-gcp-core/pom.xml
- addons/nuxeo-ai-gcp-package/pom.xml
- addons/nuxeo-ai-gcp-package/src/main/assemble/assembly.xml
- addons/nuxeo-ai-image-quality-core/pom.xml
- addons/nuxeo-ai-image-quality-package/pom.xml
- addons/nuxeo-ai-image-quality-package/src/main/assemble/assembly.xml
- addons/pom.xml
- nuxeo-ai-core-package/src/main/assemble/assembly.xml
- pom.xml
- tools/release.sh
> 10.10/fix AICORE-423 deploy

- Jenkinsfile
- addons/nuxeo-ai-aws-core/pom.xml
- addons/nuxeo-ai-aws-package/pom.xml
- addons/nuxeo-ai-aws-package/src/main/assemble/assembly.xml
- addons/nuxeo-ai-gcp-core/pom.xml
- addons/nuxeo-ai-gcp-package/pom.xml
- addons/nuxeo-ai-gcp-package/src/main/assemble/assembly.xml
- addons/nuxeo-ai-image-quality-core/pom.xml
- addons/nuxeo-ai-image-quality-package/pom.xml
- addons/nuxeo-ai-image-quality-package/src/main/assemble/assembly.xml
- addons/pom.xml
- nuxeo-ai-core-package/src/main/assemble/assembly.xml
- nuxeo-ai-model/src/test/resources/OSGI-INF/bulk-export-test.xml
Backport #383
Fix Maven deploy
AICORE-328: don't push Packages as Maven artifacts, instead attach empty dummy packages
> fix(AICORE-423): mvn deploy

- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/pipeline-config.xml.nxftl
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/functions/SaveEnrichmentFunction.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/BulkEnrichmentTest.java
- nuxeo-ai-pipes/src/main/java/org/nuxeo/ai/pipes/filters/NoVersionFilter.java
- nuxeo-ai-pipes/src/main/java/org/nuxeo/ai/pipes/services/PipeDescriptor.java
- nuxeo-ai-pipes/src/main/resources/OSGI-INF/pipeline-contrib.xml
- nuxeo-ai-pipes/src/test/java/org/nuxeo/ai/pipes/events/EventPipesTest.java
- nuxeo-ai-pipes/src/test/java/org/nuxeo/ai/pipes/functions/FunctionsTest.java
- nuxeo-ai-pipes/src/test/resources/OSGI-INF/stream-pipes-test.xml
- nuxeo-ai-pipes/src/test/resources/ai-dam-config.xml
> AICORE-471: filter out versions in enrichments and no save on immutable

- charts/preview/Chart.yaml
- tools/release.sh
- tools/sprint.sh
fix(AICORE-462): chart version 3.1.2-SNAPSHOT
fix(AICORE-462): version replacement on release and new sprint
- nuxeo-ai-internal/pom.xml
- charts/preview/Chart.yaml
> fix AICORE-462 release version replacement

- Jenkinsfile
- pom.xml
- chore(deps): parameterize webui version
- ~chore(AICORE-491): webui 3.0.3~
> fix AICORE-491 webui

- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/DedupConstants.java
- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/listeners/DedupListener.java
- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/listeners/DocumentIndexedListener.java
- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/operation/DedupDeleteIndexOperation.java
- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/operation/FindSimilar.java
- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/services/SimilarContentService.java
- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/services/SimilarServiceComponent.java
- nuxeo-ai-similar-content/src/main/resources/OSGI-INF/similar-content-listener-contrib.xml
- nuxeo-ai-similar-content/src/test/java/org/nuxeo/ai/similar/content/listeners/DeduplicationListenersTest.java
- nuxeo-ai-similar-content/src/test/java/org/nuxeo/ai/similar/content/listeners/DocumentIndexedListenerTest.java
- nuxeo-ai-similar-content/src/test/java/org/nuxeo/ai/similar/content/mock/ResolveDuplicatesListener.java
- nuxeo-ai-similar-content/src/test/resources/OSGI-INF/mock-listener-contrib.xml
- nuxeo-ai-similar-content/src/test/resources/mappings/get_find.json
* AICORE-528: duplications found event on create/update
> AICORE-528: duplications found event on create/update (#492)

- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/BulkEnrichmentAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/ModelProperty.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/ModelJsonEnricher.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/ModelServingService.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/ModelServingServiceImpl.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/serving/SuggestionOp.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/SuggestionOpTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/model/serving/TestModelServing.java
- nuxeo-ai-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-ai/nuxeo-ai.html
> AICORE-531: grouped model inputs (#479)

- nuxeo-ai-core/src/main/java/org/nuxeo/ai/utils/DateUtils.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/listeners/ContinuousExportListener.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/listeners/InvalidateModelDefinitionsListener.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/export/DatasetExportService.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/export/DatasetExportServiceImpl.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/model/export/DatasetExportUpdaterOperation.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/listeners/ContinuousExportListenerTest.java
* AICORE-557: export query modification + tests improvements
* tracking running exports per model
> AICORE-557: export query modification + tests improvements (#503)

- nuxeo-ai-model/src/main/java/org/nuxeo/ai/adapters/Model.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/listeners/ContinuousExportListener.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/cloud/CloudClientTest.java
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/listeners/ContinuousExportListenerTest.java
- nuxeo-ai-model/src/test/resources/mappings/nuxeo_get_by_models_by_ds.json
* AICORE-567: continuous listener distinct models
> AICORE-567: continuous listener distinct models (#520)

- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/endpoint/Rekognition.java
- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/enrichment/async/DetectSegmentEnrichmentProvider.java
- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/metrics/AWSMetrics.java
- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/rekognition/RekognitionService.java
- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/rekognition/RekognitionServiceImpl.java
- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/rekognition/listeners/AsyncSegmentResultListener.java
- addons/nuxeo-ai-aws-core/src/main/resources/OSGI-INF/listener-contrib.xml
- addons/nuxeo-ai-aws-core/src/main/resources/OSGI-INF/rekognition-service.xml
- addons/nuxeo-ai-aws-package/src/main/resources/install/templates/nuxeo-ai-aws/config/ai-aws-config.xml.nxftl
- nuxeo-ai-core/src/main/resources/directories/ai_kinds.csv
Adding a new enrichment type for aws rekogniton video segment detection
https://docs.aws.amazon.com/rekognition/latest/dg/segments.html
> AICORE-573: Add support for Rekognition Video Segment detection

- .github/workflows/build_and_test.yml
- .github/workflows/pipeline_release.yml
- fix(AICORE-588): cleanup aws steps
- chore(AICORE-588): add release pipeline
> Pipeline master

- addons/nuxeo-ai-aws-core/src/main/java/org/nuxeo/ai/enrichment/async/TranscribeEnrichmentProvider.java
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-pipelines-configurable-batch-config.xml.nxftl
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/bulk/RecordWriterDescriptor.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/enrichment/EnrichmentOp.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/BulkDatasetExportAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/BulkEnrichmentAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUpdateComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUploadComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportInitComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/RecordWriterBatchComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/cloud/NuxeoCloudClient.java
- nuxeo-ai-model/src/main/resources/OSGI-INF/ai-bulk.xml
- nuxeo-ai-model/src/test/java/org/nuxeo/ai/bulk/DatasetExportTest.java
- nuxeo-ai-model/src/test/resources/OSGI-INF/ai-bulk-small-test.xml
- nuxeo-ai-pipes/src/main/java/org/nuxeo/ai/pipes/functions/PropertyUtils.java
* AICORE-591: relax constraints for exported corpus
* use batch id for key in streams
> AICORE-591: relax constraints for exported corpus (#544)

- .github/workflows/pipeline_pr.yaml
- README.md
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/config/ai-pipelines-configurable-batch-config.xml.nxftl
- nuxeo-ai-core-package/src/main/resources/install/templates/nuxeo-ai-core/nuxeo.defaults
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/enrichment/EnrichingStreamProcessor.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/functions/RaiseEnrichmentEvent.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/tensorflow/TFRecordWriter.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/BulkDatasetExportAction.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUpdateComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUploadComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportDoneComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportInitComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/RecordWriterBatchComputation.java
- nuxeo-ai-model/src/main/resources/OSGI-INF/ai-bulk.xml
- nuxeo-ai-model/src/test/resources/OSGI-INF/bulk-export-test.xml
- nuxeo-ai-pipes/src/main/java/org/nuxeo/ai/pipes/functions/PropertyUtils.java
- nuxeo-ai-pipes/src/main/java/org/nuxeo/ai/pipes/services/PipeDescriptor.java
* task(AICORE-594): refactoring export pipeline
> task(AICORE-594): refactoring export pipeline

- nuxeo-ai-similar-content/src/main/java/org/nuxeo/ai/similar/content/services/SimilarServiceComponent.java
* AICORE-596: bulk status for indexing stored in kvs
* add status prefix
> AICORE-596: bulk status for indexing stored in kvs (#551)

- nuxeo-ai-core/src/main/java/org/nuxeo/ai/bulk/AbstractRecordWriter.java
- nuxeo-ai-core/src/main/java/org/nuxeo/ai/tensorflow/TFRecordWriter.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/adapters/DatasetExport.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUpdateComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/DatasetUploadComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportHelper.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/ExportInitComputation.java
- nuxeo-ai-model/src/main/java/org/nuxeo/ai/bulk/RecordWriterBatchComputation.java
* AICORE-599: use batch id while passing through the streams
> AICORE-599: use batch id while passing through the streams (#559)

- .github/workflows/build_and_test.yml
This is a quick fix related to https://github.com/nuxeo/nuxeo-ai/pull/602
> AICORE-615: Fix workflow package upload issue

- addons/nuxeo-ai-aws-core/pom.xml
- addons/nuxeo-ai-aws-package/pom.xml
- addons/nuxeo-ai-gcp-core/pom.xml
- addons/nuxeo-ai-gcp-package/pom.xml
- addons/nuxeo-ai-image-quality-core/pom.xml
- addons/nuxeo-ai-image-quality-package/pom.xml
- addons/pom.xml
- charts/preview/Chart.yaml
- nuxeo-ai-config/pom.xml
- nuxeo-ai-core-package/pom.xml
- nuxeo-ai-core/pom.xml
- nuxeo-ai-internal/pom.xml
- nuxeo-ai-model/pom.xml
- nuxeo-ai-pipes/pom.xml
- nuxeo-ai-similar-content/pom.xml
- nuxeo-ai-web-ui/pom.xml
- pom.xml
This pull request will publish release 2.7.21. The previous release was 2.7.20 - see: https://github.com/nuxeo/nuxeo-ai/pull/598 and https://github.com/nuxeo/nuxeo-ai/pull/599
This includes the following two changes since v2.7.20:
- https://github.com/nuxeo/nuxeo-ai/pull/602
- https://github.com/nuxeo/nuxeo-ai/pull/603
- https://github.com/nuxeo/nuxeo-ai/pull/604
It additionally includes the following change within v2.7.20 after v2.7.19 which did not successfully deploy to Nexus or the Marketplace:
- https://github.com/nuxeo/nuxeo-ai/pull/597
> Release 2.7.21

- addons/nuxeo-ai-aws-core/pom.xml
- addons/nuxeo-ai-aws-package/pom.xml
- addons/nuxeo-ai-gcp-core/pom.xml
- addons/nuxeo-ai-gcp-package/pom.xml
- addons/nuxeo-ai-image-quality-core/pom.xml
- addons/nuxeo-ai-image-quality-package/pom.xml
- addons/pom.xml
- charts/preview/Chart.yaml
- nuxeo-ai-config/pom.xml
- nuxeo-ai-core-package/pom.xml
- nuxeo-ai-core/pom.xml
- nuxeo-ai-internal/pom.xml
- nuxeo-ai-model/pom.xml
- nuxeo-ai-pipes/pom.xml
- nuxeo-ai-similar-content/pom.xml
- nuxeo-ai-web-ui/pom.xml
- pom.xml
Release 2.7.21 has been published: https://github.com/nuxeo/nuxeo-ai/pull/605
https://github.com/nuxeo/nuxeo-ai/actions/runs/4888822623
> Post release 2.7.21

- .github/workflows/build_and_test.yml
- .github/workflows/pipeline_release.yml
This will send a slack notification on deployment failures.
> AICORE-618: Add deploy failure slack notifications

- nuxeo-ai-model/src/main/java/org/nuxeo/ai/cloud/NuxeoCloudClient.java
We have encountered a NullPointerException within the NuxeoCloudClient, when creating and uploading dataset batches. A blob file was null, causing the program to run into into a NullPointerException within the FileBlob constructor. This commit makes the NuxeoCloudClient more resilient. We now check for null blob files within the createBatch() and uploadDataset() methods.
https://jira.nuxeo.com/browse/AICORE-626
> AICORE-626: Make NuxeoCloudClient dataset uploads more resilient

- addons/nuxeo-ai-aws-core/pom.xml
- addons/nuxeo-ai-aws-package/pom.xml
- addons/nuxeo-ai-gcp-core/pom.xml
- addons/nuxeo-ai-gcp-package/pom.xml
- addons/nuxeo-ai-image-quality-core/pom.xml
- addons/nuxeo-ai-image-quality-package/pom.xml
- addons/pom.xml
- charts/preview/Chart.yaml
- nuxeo-ai-config/pom.xml
- nuxeo-ai-core-package/pom.xml
- nuxeo-ai-core/pom.xml
- nuxeo-ai-internal/pom.xml
- nuxeo-ai-model/pom.xml
- nuxeo-ai-pipes/pom.xml
- nuxeo-ai-similar-content/pom.xml
- nuxeo-ai-web-ui/pom.xml
- pom.xml
This pull request will publish release 2.7.23. The previous release was 2.7.22 - see: https://github.com/nuxeo/nuxeo-ai/pull/618 and https://github.com/nuxeo/nuxeo-ai/pull/619
The release before that was 2.7.21 - see: https://github.com/nuxeo/nuxeo-ai/pull/605 and https://github.com/nuxeo/nuxeo-ai/pull/606
This release includes the following two changes:
- https://github.com/nuxeo/nuxeo-ai/pull/626
- https://github.com/nuxeo/nuxeo-ai/pull/627
> Release 2.7.23

- nuxeo-ai-model/src/main/java/org/nuxeo/ai/cloud/NuxeoCloudClient.java
We have encountered a NullPointerException within the NuxeoCloudClient, when creating and uploading dataset batches. A blob file was null, causing the program to run into into a NullPointerException within the FileBlob constructor. This commit makes the NuxeoCloudClient more resilient. We now check for null blob files within the createBatch() and uploadDataset() methods.
https://jira.nuxeo.com/browse/AICORE-626
This is identical to the following fix for 10.10:
- https://github.com/nuxeo/nuxeo-ai/pull/627
> AICORE-626: Make NuxeoCloudClient dataset uploads more resilient (Forward port from 2.7.23)

- addons/nuxeo-ai-aws-core/pom.xml
- addons/nuxeo-ai-aws-package/pom.xml
- addons/nuxeo-ai-gcp-core/pom.xml
- addons/nuxeo-ai-gcp-package/pom.xml
- addons/nuxeo-ai-image-quality-core/pom.xml
- addons/nuxeo-ai-image-quality-package/pom.xml
- addons/pom.xml
- charts/preview/Chart.yaml
- charts/utests/Chart.yaml
- nuxeo-ai-config/pom.xml
- nuxeo-ai-core-package/pom.xml
- nuxeo-ai-core/pom.xml
- nuxeo-ai-internal/pom.xml
- nuxeo-ai-model/pom.xml
- nuxeo-ai-pipes/pom.xml
- nuxeo-ai-similar-content/pom.xml
- nuxeo-ai-web-ui/pom.xml
- pom.xml
This pull request will publish release 3.5.13 when merged. The previous release was 3.5.12.
- https://github.com/nuxeo/nuxeo-ai/pull/617
- https://github.com/nuxeo/nuxeo-ai/pull/620
Release 3.5.13 includes the following changes:
- https://github.com/nuxeo/nuxeo-ai/pull/625
- https://github.com/nuxeo/nuxeo-ai/pull/629
These were previously included in release 2.7.23 for 10.10:
- https://github.com/nuxeo/nuxeo-ai/pull/628
> Release 3.5.13
